### ISSUE TITLE
如何在WPF中导入自定义任务和相关python代码

### ISSUE THREAD

**Issue by SunFrosty** [SweetSmellFox/MFAWPF#12]

**Comment by SunFrosty** [comment]
主要功能在自定义python中实现，在pipeline里只有一个框架

**Comment by SweetSmellFox** [comment]
这个在maafw1.8可以在interface中通过exec agent来注册自定义事件，但是在2.0中maafw把exec agent移除了，导致没法通过配置文件来注册自定义事件，预计要等maafw2.1才有
