### ISSUE TITLE
mumu模拟器多开，有时候会关错了模拟器

### ISSUE THREAD

**Issue by a16797** [SweetSmellFox/MFAWPF#39]
如果0号模拟器开着，手动运行2号，再运行MFA。MFA会关掉0号
如果0号模拟器开着，MFA运行2号，MFA会关掉2号

-------------------
<details>
<summary>多开2个模拟器</summary>

![image](https://github.com/user-attachments/assets/26f32ccf-9ebe-4428-a13b-3bf6e0a9a1cc)
![image](https://github.com/user-attachments/assets/0b04a4a3-70f9-4224-a3b4-0e49936d1e71)

</details>

执行完mfa之后，会把默认模拟器（碧蓝）关了
[maa.log](https://github.com/user-attachments/files/17437520/maa.log)

**Comment by SweetSmellFox** [comment]
因为mfa目前只能关闭自己启动的模拟器，如果不是自己启动的话，是根据模拟器名字关闭，所以有概率误关（

**Comment by a16797** [comment]
好的。大佬看看隔壁发的，为啥没日志。
