### ISSUE TITLE
更新到v1.2.1.6之后推送新版本MFATools.exe打开不了

### ISSUE THREAD

**Issue by Hiro1137** [SweetSmellFox/MFAWPF#43]
v1.2.1.5时配置好install.yml推送新版本一切正常，更新到v1.2.1.6后同一个install.yml推送新版本之后MFATools.exe就打不开了
[1215](https://wwvo.lanzouo.com/iQr2C2d5r34f)
[1216](https://wwvo.lanzouo.com/ir4Qf2d5r3ta)
[install.txt](https://github.com/user-attachments/files/17481363/install.txt)

**Comment by SweetSmellFox** [comment]
重新发布了1.2.1.6，你再install.yml推送就好了
