### ISSUE TITLE
添加“启动mfa后直接运行”的选项

### ISSUE THREAD

**Issue by LinYanxi0** [SweetSmellFox/MFAWPF#46]
rt，因为没有这个所以还在用之前的命令行（笑）
有了tt

**Comment by SweetSmellFox** [comment]
这个在高级设置里面把 `启动后操作` 从 `无` 改为 `启动脚本就行`

**Comment by SweetSmellFox** [comment]
![27d04e7a379b8d20687bff9cd9dd186a](https://github.com/user-attachments/assets/ed4763ac-ff94-4b18-9f7e-98e9e7e4d0ad)
