### ISSUE TITLE
從v1.2.3.01開始,MFAWPF打不開

### ISSUE THREAD

**Issue by swient** [SweetSmellFox/MFAWPF#63]
無法開啟後,我改嘗試使用 Visual Studio 2022 建置專案來運行,得到以下錯誤
System.IO.IOException
  HResult=0x80131620
  Message=找不到資源 'app.xaml'。
  Source=PresentationFramework
  StackTrace: 
   於 MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
   於 System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   於 MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
   於 System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   於 MFAWPF.App.InitializeComponent() 在 C:\Users\leo09\Shortcut\Downloads\MFAWPF-1.2.3.3\MFAWPF-1.2.3.3\App.xaml:行 1 中
   於 MFAWPF.App.Main()
根據commit的紀錄,這個錯誤是從這裡開始出現的https://github.com/SweetSmellFox/MFAWPF/commit/eacc10012919dbcab3152c9c4ba6e6767c505e60

**Comment by SweetSmellFox** [comment]
我用Rider有概率也会出现，我的解决办法是把 <ResourceDictionary Source="pack://application:,,,/HandyControl;component/themes/theme.xaml"/>改成 <ResourceDictionary Source="pack://application:,,,/HandyControl;component/themes/theme.theme.xaml"/>运行一下，然后再改回<ResourceDictionary Source="pack://application:,,,/HandyControl;component/themes/theme.theme.xaml"/>运行就行

**Comment by SweetSmellFox** [comment]
我用Rider也有概率会出现，我的解决方法是把ResourceDictionary Source="pack://application:,,,/HandyControl;component/themes/theme.xaml" 改成 ResourceDictionary Source="pack://application:,,,/HandyControl;component/themes/theme.theme.xaml" 运行一下，报错一下，然后再改回ResourceDictionary Source="pack://application:,,,/HandyControl;component/themes/theme.xaml" 就行了

**Comment by swient** [comment]
我遇到的情況是我從Releases裡下載編譯好的版本也打不開

**Comment by SweetSmellFox** [comment]
> 我遇到的情況是我從Releases裡下載編譯好的版本也打不開

试试v1.2.3.3运行后，同目录下有没有logs文件夹，看一下里面的报错

**Comment by swient** [comment]
沒有生成logs文件夹
https://github.com/user-attachments/assets/ffaa0337-a93d-4ea5-988d-172b62a2cdf4

**Comment by SweetSmellFox** [comment]
> 沒有生成logs文件夹 https://github.com/user-attachments/assets/ffaa0337-a93d-4ea5-988d-172b62a2cdf4
在NLog.config里的 ```<Target></Target> ```里添加    ``` <target name="file" xsi:type="File" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message}"  archiveEvery="Day"
            maxArchiveFiles="3"
            archiveAboveSize="10000"/> ```

**Comment by swient** [comment]
似乎還是沒有生成
![NLog config - Microsoft Visual Studio 2024_12_24 上午 11_59_09](https://github.com/user-attachments/assets/41fff3f7-487f-4c53-b19c-a0c477054d56)

**Comment by SweetSmellFox** [comment]
我重新发布了v1.2.3.3，你下载一下试试

**Comment by swient** [comment]
問題依舊

https://github.com/user-attachments/assets/5ad5280f-9199-4d12-834c-7a5620a6f463

**Comment by SweetSmellFox** [comment]
日志都没运行，应该是前置炸了，你可以用别的设备运行排查一下，也有可能是net core问题

**Comment by SweetSmellFox** [comment]
> 問題依舊
> 
>  MFAWPF_Can.t_open.mp4

能启动cli吗

**Comment by swient** [comment]
最新的v1.2.3.3沒看到MaaPiCli.exe,運行v1.2.3.1的MaaPiCli.exe得到以下結果
![C__Users_leo09_Shortcut_Downloads_MFAWPF-v1 2 3 1_MaaPiCli exe 2024_12_24 下午 03_29_56](https://github.com/user-attachments/assets/d5f696fd-66d8-4399-b12a-2b845e1a79b8)

**Comment by SweetSmellFox** [comment]
你发一下的interface.json打所有内容

**Comment by swient** [comment]
從別的地方找來了interface.json
![C__Users_leo09_Shortcut_Downloads_MFAWPF-v1 2 3 1_MaaPiCli exe 2024_12_24 下午 03_40_45](https://github.com/user-attachments/assets/3d7db20e-5b0e-47be-95c9-6cf09e454b66)

**Comment by swient** [comment]
![C__Users_leo09_Shortcut_Downloads_MFAWPF-v1 2 3 1_MaaPiCli exe 2024_12_24 下午 03_44_11](https://github.com/user-attachments/assets/6e5069ec-0ca2-4f12-b1e2-6312860d2c47)

**Comment by Windsland52** [comment]
看起来运行cli没有问题

**Comment by SweetSmellFox** [comment]
把UICuliture全删除也可以

**Comment by Windsland52** [comment]
好像是系统语言导致的问题？ https://github.com/MaaXYZ/M9A/issues/295
